// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebFilePublishVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "WebFilePublishVSIX.560f5ecd-9894-4105-b2ae-5899c8ad2048";
        public const string Name = "WebFilePublishVSIX";
        public const string Description = @"publisher for web VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "mirror space";
        public const string Tags = "";
    }
}
