// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebFilePublishVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string WebFilePublishVSIXString = "383731c3-506b-4c02-87be-5dd6ac36d434";
        public static Guid WebFilePublishVSIX = new Guid(WebFilePublishVSIXString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int menuIdTop = 0x0001;
        public const int groupIdTop = 0x0002;
        public const int groupIdActiveFile = 0x0015;
        public const int cmdidPublishActiveFile = 0x001F;
        public const int groupIdFile = 0x0016;
        public const int cmdidPublishFile = 0x0020;
        public const int groupIdDir = 0x0017;
        public const int cmdidPublishDir = 0x0021;
        public const int groupIdWeb = 0x0018;
        public const int cmdidPublishWeb = 0x0022;
    }
}